version: '3'
services:
  minio:
    image: quay.io/minio/minio
    container_name: minio_tdk
    environment:
      - MINIO_ROOT_USER=minio_root
      - MINIO_ROOT_PASSWORD=minio_root
      - MINIO_ACCESS_KEY=8HK3OLFyhpm6FCVCNPkY
      - MINIO_SECRET_KEY=le6lKt9TlJXVq5EYQjngXJVtrcWfRG4WhxYdTmuU
    volumes:
      - ./minIO/data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command:
      - minio
      - server
      - /data
      - --console-address
      - ":9001"